In [27]:
import pandas as pd

In [28]:
dataset = pd.read_csv("train.csv")
dataset.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [29]:
dataset.shape

(20800, 5)

In [30]:
dataset.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [31]:
dataset = dataset.dropna()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [32]:
dataset.head(10)

id                                              title  \
0    0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1    1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2    2                  Why the Truth Might Get You Fired   
3    3  15 Civilians Killed In Single US Airstrike Hav...   
4    4  Iranian woman jailed for fictional unpublished...   
5    5  Jackie Mason: Hollywood Would Love Trump if He...   
7    7  Benoît Hamon Wins French Socialist Party’s Pre...   
9    9  A Back-Channel Plan for Ukraine and Russia, Co...   
10  10  Obama’s Organizing for Action Partners with So...   
11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                          author  \
0                  Darrell Lucus   
1                Daniel J. Flynn   
2             Consortiumnews.com   
3                Jessica Purkiss   
4                 Howard Portnoy   
5                Daniel Nussbaum   
7                Alissa J. Rubin   
9   Megan Twohey and Scott Shane   
10                   Aaron Klein   
11               Chris Tomlinson   

                                                 text  label  
0   House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1   Ever get the feeling your life circles the rou...      0  
2   Why the Truth Might Get You Fired October 29, ...      1  
3   Videos 15 Civilians Killed In Single US Airstr...      1  
4   Print \nAn Iranian woman has been sentenced to...      1  
5   In these trying times, Jackie Mason is the Voi...      0  
7   PARIS  —   France chose an idealistic, traditi...      0  
9   A week before Michael T. Flynn resigned as nat...      0  
10  Organizing for Action, the activist group that...      0  
11  The BBC produced spoof on the “Real Housewives...      0

In [33]:
print(dataset.shape)
dataset.reset_index(inplace = True)
title = dataset["title"]
title.head()

(18285, 5)


0    House Dem Aide: We Didn’t Even See Comey’s Let...
1    FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                    Why the Truth Might Get You Fired
3    15 Civilians Killed In Single US Airstrike Hav...
4    Iranian woman jailed for fictional unpublished...
Name: title, dtype: object

In [34]:
import nltk
import re
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [35]:
title_list = []
stemmer = PorterStemmer()

for i in range(title.shape[0]):
    temp = re.sub('[^a-zA-Z]', " ", title[i])
    temp = re.sub('\s+', ' ', temp)
    temp = temp.lower()
    temp = temp.split()
    temp = [stemmer.stem(words) for words in temp if words not in set(stopwords.words('english'))]
    temp = ' '.join(temp)
    title_list.append(temp)

title_list

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [46]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [42]:
title_list_1 = []
stemmer_1 = PorterStemmer()
sum = 0

for i in range(title.shape[0]):
    temp = re.sub('[^a-zA-Z]', " ", title[i])
    temp = re.sub('\s+', ' ', temp)
    temp = temp.lower()
    temp = temp.split()
    temp = [words for words in temp if words not in set(stopwords.words('english'))]
    sum = sum + len(temp)

In [43]:
sum # number of total words present in title after text preprocessing

159550

In [38]:
voc_size = 10000
one_hot_repre = [one_hot(words, voc_size) for words in title_list]
one_hot_repre

[[7627, 1730, 4216, 7020, 1192, 2973, 3908, 2801, 1238, 8245],
 [5667, 3027, 98, 8517, 4905, 5877, 2031],
 [4849, 4831, 4812, 7263],
 [5169, 2669, 2757, 7730, 6242, 9156],
 [5599, 4905, 5277, 1159, 9009, 4610, 4905, 1659, 2569, 6348],
 [9710,
  7,
  4261,
  3203,
  3013,
  6792,
  19,
  6411,
  9341,
  9613,
  3511,
  5994,
  9597,
  4277,
  2031],
 [5043, 7749, 5803, 4988, 9299, 8966, 2307, 3255, 4518, 2738, 1441],
 [6750, 2479, 4526, 6443, 1303, 9771, 6792, 4005, 4518, 2738, 1441],
 [9421, 2636, 7464, 6168, 8085, 5753, 7056, 4822, 6792, 3191],
 [747, 29, 7345, 5694, 4736, 5655, 8184, 1944],
 [4920, 269, 3577, 7323, 6510, 3580, 5250, 6192, 1516, 6412, 9466],
 [7730, 3544, 1192, 5753, 6792, 1303],
 [2185, 5029, 5821, 7450, 181, 9365, 496, 8277, 7547],
 [1757, 6952, 4887, 9580, 2738, 1571, 6643, 4518, 2738, 1441],
 [963, 3760, 2263, 2920, 2122, 4518, 2738, 1441],
 [6300, 5109, 2125, 9372, 8596, 4471, 7627, 6838, 7034, 2425],
 [9783, 7403, 3027],
 [4975, 3923, 5079, 7762, 6792, 3674, 101

In [44]:
input = pad_sequences(one_hot_repre, padding = "pre", maxlen = 20)
input

array([[   0,    0,    0, ..., 2801, 1238, 8245],
       [   0,    0,    0, ..., 4905, 5877, 2031],
       [   0,    0,    0, ..., 4831, 4812, 7263],
       ...,
       [   0,    0,    0, ..., 4518, 2738, 1441],
       [   0,    0,    0, ..., 4050, 6767, 9614],
       [   0,    0,    0, ..., 1479, 7143, 6766]])

In [47]:
model = Sequential()
model.add(Embedding(voc_size, 40, input_length = 20))
model.add(LSTM(100))
model.add(Dense(1, activation = "sigmoid"))
model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            400000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 456,501
Trainable params: 456,501
Non-trainable params: 0
_________________________________________________________________
None


In [48]:
input[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 7627,
       1730, 4216, 7020, 1192, 2973, 3908, 2801, 1238, 8245])

In [51]:
y = dataset["label"]

(18285,)

In [54]:
import numpy as np
input = np.array(input)
y = np.array(y)

In [55]:
input.shape, y.shape

((18285, 20), (18285,))

In [57]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(input, y, test_size = 0.33, random_state = 0)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((12250, 20), (12250,), (6035, 20), (6035,))

In [58]:
model.fit(x_train, y_train, validation_data =(x_test, y_test), epochs = 10, batch_size = 64)

Epoch 1/10
192/192 [==============================] - 35s 118ms/step - loss: 0.3344 - accuracy: 0.8362 - val_loss: 0.1887 - val_accuracy: 0.9206
Epoch 2/10
192/192 [==============================] - 21s 111ms/step - loss: 0.1335 - accuracy: 0.9480 - val_loss: 0.2032 - val_accuracy: 0.9191
Epoch 3/10
192/192 [==============================] - 23s 122ms/step - loss: 0.0851 - accuracy: 0.9691 - val_loss: 0.2184 - val_accuracy: 0.9201
Epoch 4/10
192/192 [==============================] - 21s 108ms/step - loss: 0.0551 - accuracy: 0.9824 - val_loss: 0.2534 - val_accuracy: 0.9178
Epoch 5/10
192/192 [==============================] - 20s 103ms/step - loss: 0.0344 - accuracy: 0.9895 - val_loss: 0.3113 - val_accuracy: 0.9193
Epoch 6/10
192/192 [==============================] - 19s 101ms/step - loss: 0.0170 - accuracy: 0.9953 - val_loss: 0.4147 - val_accuracy: 0.9138
Epoch 7/10
192/192 [==============================] - 19s 97ms/step - loss: 0.0087 - accuracy: 0.9976 - val_loss: 0.4499 - val_acc

In [66]:
y_pred = model.predict(x_test)

189/189 [==============================] - 7s 27ms/step


In [72]:
for i in range(y_pred.shape[0]):
    if(y_pred[i] < 0.5):
        y_pred[i] = 0
    else:
        y_pred[i] = 1

In [76]:
from sklearn.metrics import confusion_matrix, accuracy_score
matrix = confusion_matrix(y_test, y_pred)
matrix

array([[3159,  230],
       [ 351, 2295]], dtype=int64)

In [77]:
score = accuracy_score(y_test, y_pred)
score

0.903728251864126

### Adding Dropout ratio

In [83]:
from tensorflow.keras.layers import Dropout
feature_vector = 40
model_1 = Sequential()
model_1.add(Embedding(voc_size, feature_vector, input_length = 20))
model_1.add(Dropout(0.3))
model_1.add(LSTM(100))
model_1.add(Dropout(0.3))
model_1.add(Dense(1, activation = "sigmoid"))
model_1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model_1.summary())

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, 20, 40)            400000    
                                                                 
 dropout_4 (Dropout)         (None, 20, 40)            0         
                                                                 
 lstm_4 (LSTM)               (None, 100)               56400     
                                                                 
 dropout_5 (Dropout)         (None, 100)               0         
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 456,501
Trainable params: 456,501
Non-trainable params: 0
_________________________________________________________________
None


In [84]:
model_1.fit(x_train, y_train, validation_data = (x_test, y_test), epochs = 10, batch_size = 64)

Epoch 1/10
192/192 [==============================] - 36s 129ms/step - loss: 0.3464 - accuracy: 0.8438 - val_loss: 0.1947 - val_accuracy: 0.9171
Epoch 2/10
192/192 [==============================] - 20s 102ms/step - loss: 0.1501 - accuracy: 0.9433 - val_loss: 0.1814 - val_accuracy: 0.9226
Epoch 3/10
192/192 [==============================] - 21s 108ms/step - loss: 0.1027 - accuracy: 0.9632 - val_loss: 0.1966 - val_accuracy: 0.9180
Epoch 4/10
192/192 [==============================] - 20s 103ms/step - loss: 0.0720 - accuracy: 0.9758 - val_loss: 0.2385 - val_accuracy: 0.9173
Epoch 5/10
192/192 [==============================] - 21s 112ms/step - loss: 0.0547 - accuracy: 0.9824 - val_loss: 0.2415 - val_accuracy: 0.9137
Epoch 6/10
192/192 [==============================] - 20s 104ms/step - loss: 0.0412 - accuracy: 0.9856 - val_loss: 0.2828 - val_accuracy: 0.9046
Epoch 7/10
192/192 [==============================] - 20s 105ms/step - loss: 0.0331 - accuracy: 0.9893 - val_loss: 0.3609 - val_ac

In [86]:
y_pred_1 = model_1.predict(x_test)

for i in range(y_pred_1.shape[0]):
    if(y_pred_1[i] < 0.5):
        y_pred_1[i] = 0
    else:
        y_pred_1[i] = 1

189/189 [==============================] - 4s 21ms/step


In [87]:
matrix_1 = confusion_matrix(y_test, y_pred_1)
matrix_1

array([[3131,  258],
       [ 298, 2348]], dtype=int64)

In [89]:
score_1 = accuracy_score(y_test, y_pred_1)
score_1

0.907870753935377